apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: atfi24mmf-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/atfi24mmf-dotnet-basic-gitops